# Generated by Django 4.2.13 on 2024-05-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuCategory', '0002_menucategory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='slug',
        ),
    ]
