POST http://127.0.0.1:8000/login
content-type: application/json

{ "username": "Ludivin", "password": "Pass1234" }

###

POST http://127.0.0.1:8000/signup
content-type: application/json

{ "username": "Ludivin4", "password": "Pass1234", "email": "test4@gmail.com" }


###

GET http://127.0.0.1:8000/api/test_token
content-type: application/json
Authorization: Token 9ce0ee7821bc8e1810de3317ce81741d599b3464

{ }