# Generated by Django 4.2.13 on 2024-06-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0002_alter_menus_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='slug',
        ),
    ]
